# Generated by Django 2.2.5 on 2019-11-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Unique_Squirrel_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Shift', models.CharField(max_length=2)),
                ('Date', models.DateField()),
                ('Age', models.CharField(blank=True, max_length=10, null=True)),
                ('Primary_Fur_Color', models.CharField(blank=True, max_length=10, null=True)),
                ('Location', models.CharField(blank=True, max_length=20, null=True)),
                ('Specific_Location', models.CharField(blank=True, max_length=30, null=True)),
                ('Running', models.BooleanField()),
                ('Chasing', models.BooleanField()),
                ('Climbing', models.BooleanField()),
                ('Eating', models.BooleanField()),
                ('Foraging', models.BooleanField()),
                ('Other_Activities', models.CharField(blank=True, max_length=20, null=True)),
                ('Kuks', models.BooleanField()),
                ('Quaas', models.BooleanField()),
                ('Moans', models.BooleanField()),
                ('Tail_flags', models.BooleanField()),
                ('Tail_twitches', models.BooleanField()),
                ('Approaches', models.BooleanField()),
                ('Indifferent', models.BooleanField()),
                ('Runs_from', models.BooleanField()),
            ],
        ),
    ]
